# Site settings
baseURL = "https://federico-carrara-portfolio.netlify.app/"
languageCode = "en-us"
title = "Portfolio website for Federico Carrara"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Federico Carrara"
  description = "Federico Carrara Portfolio website"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Federico"
    subtitle = "Welcome to my portfolio of projects"
    menu = "Menu"
   # Optional logo as brand stored in img/
    # logo = "logo.png"

   [[params.navigation.links]]
     name = "Home"
      url = "#"

    #[[params.navigation.links]]
     # name = "Projects"
      # url = "Projects"

    # [[params.navigation.links]]
      #name = "Generic Blog"  
      #url = "blogs/ipsum"

   # [[params.navigation.links]]
     # name = "Elements"
    #  url = "elements.html"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
   # [[params.navigation.button1]]
    #  name = "Get Started"
     #  url = "blogs"

    # Button Style 2
    #[[params.navigation.button2]]
     # name = "Log In"
      # url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, my name is Federico"
    subtitle = "I am an italian student at London Business School. I'm passionate about art and I'm an avid reader. Leave me a message if you want ;)"
    buttonText = "Get started"


  # Tiles Section
  [params.tiles]
  
    enable = true
    # Display your showcases here.
    


    [[params.tiles.showcase]]
      title = "Climate change and temperature anomalies"
      subtitle = "An impressive analysis made using R"
      image = "PIC7.jpg"
      url = "blogs/blog2"

    [[params.tiles.showcase]]
      title = "A volunteering association I support"
      subtitle = "We need your help!"
      image = "PIC10.jpeg"
      url = "post/blog6"
    

    [[params.tiles.showcase]]
      title = "Who is better, Tim Burton or Steven Spielberg?"
      subtitle = "My favourite movies directors by far"
      image = "PIC2.jpg"
      url = "blogs/blog3"

    [[params.tiles.showcase]]
      title = "Where do people drink the most alcohol?"
      subtitle = "My first project at LBS"
      image = "PIC1.jpg"
      url = "blogs/blog1"
            

   # [[params.tiles.showcase]]
    #  title = "Final project"
     # subtitle = "Work in progress"
      # image = "pic05.jpg"
       # url = "blogs/ipsum"

    #[[params.tiles.showcase]]
     # title = "Final project"
      # subtitle = "work in progress"
      # image = "pic06.jpg"
      # url = "blogs/ipsum"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/con tent/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "My experience with R at London Business School"
    subtitle = """I hope will enjoy reading the porfolio of some of my projects for the Data Analytics class at London Business School. It was my first time coding, I struggled at times but I'm proud of what I've learnt and achieved. I reallly hope you will enjoy going through my projects."""
    buttonText = "Get started"
    url = "blogs"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    formEmail = "fcarrara.mfa2021@london.edu"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "fcarrara.mfa2021@london.edu"

   [[params.contact.phone]]
    title = "Phone"
    phone = "020 7000 7000"

    [[params.contact.address]]
    title = "Address"
    street = "Regent's Park, London NW1 4SA"
    #city = "City, ST 00000"
    country = "United Kingdom"

  # Footer section
  [params.footer]
    enable = true
    #copyright = "Company Name"

    # Uses font awesome icons
    #[[params.footer.social]]
      #icon = "fa-twitter"
      #url= "https://www.twitter.com"
      #label = "Twitter"

   # [[params.footer.social]]
      # icon = "fa-facebook"
      # url= "https://www.facebook.com/federico.carrara.7/"
      # label = "Facebook"

    # [[params.footer.social]]
      # icon = "fa-instagram"
      # url= "https://www.instagram.com"
      # label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://github.com/FedericoC22/my_website.git"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/federico-carrara-604742130/"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
