---
title: "Who is better, Tim Burton or Steven Spielberg?"
author: "Federico Carrara"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
---


```{r, setup, echo=FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
options(digits = 3)

# default figure size
knitr::opts_chunk$set(
  fig.width=6.75, 
  fig.height=6.75,
  fig.align = "center"
)
```


```{r load-libraries, echo=FALSE}
library(tidyverse)  # Load ggplot2, dplyr, and all the other tidyverse packages
library(mosaic)
library(ggthemes)
library(GGally)
library(readxl)
library(here)
library(skimr)
library(janitor)
library(broom)
library(tidyquant)
library(infer)
library(openintro)
library(tidyquant)
```



# IMDB ratings: Differences between directors

Let's analyse the differences between directors by building confidence intervals

```{r load-movies-data,echo=FALSE}
movies <- read_csv(here::here("data", "movies.csv"))
```


```{r}

directors_ci <- movies %>%
  filter(director %in% c("Steven Spielberg", "Tim Burton")) %>%
  filter(!is.na(rating)) %>% 
  group_by(director) %>%
  summarise(
	mean_rating = mean(rating),
            sd_rating = sd(rating),
            count = n(),
            tcritical = qt(.975, count-1),
            ste = sd_rating/sqrt(count),
            margin_of_error = tcritical*ste,
            ci_low = mean_rating - margin_of_error,
            ci_high = mean_rating + margin_of_error
	)

ggplot(directors_ci,
       aes(y = reorder(director, mean_rating),
           x = mean_rating,
           colour = director)) +
  geom_point(size=2) +
  geom_errorbar(width = .1, aes(xmin = ci_low, xmax = ci_high), lwd = 1.75) +
  geom_text(aes(label=round(mean_rating,2)),hjust=0.5, vjust=-2,
            size=5) +
  geom_rect(mapping = aes(xmin = 7.27, 
                          xmax = 7.33, 
                          ymin = 0, 
                          ymax = 3), 
            colour = "grey", 
            alpha= 0.4) +
  labs(x = "Mean IMDB Rating",
       y = " ",
       title = "Do Spielberg and Burton have the same mean IMDB rating?",
       subtitle = "95% confidence intervals overlap") +
  theme(legend.position = "none") +
  theme_bw() +
  theme(legend.position = "none")


```

Confidence intervals clearly show that Steven Spielberg has higher IMDb ratings 

```{r}

# Ho: Mean rating for Steven Spielberg and Tim Burton show difference = 0
# H1: Mean rating for Steven Spielberg and Tim Burton show difference != 0

#use t.test
directors <- movies %>%
  filter(director %in% c("Steven Spielberg","Tim Burton")) 
  t.test(rating ~ director, data = directors)

library(infer)
  
#use infer package
obs_diff_rating <-directors %>%
  specify(rating ~ director) %>%
  calculate(stat = "diff in means", order = c('Steven Spielberg', 'Tim Burton'))

null_rating <- directors %>%
  specify(rating ~ director) %>%
  hypothesize(null = "independence") %>%
  generate(reps = 1000, type = "permute") %>%
  calculate(stat = "diff in means", order = c('Steven Spielberg', 'Tim Burton'))

null_rating %>% visualize() +
  shade_p_value(obs_stat = obs_diff_rating, direction = "two-sided")

null_rating %>%
  get_p_value(obs_stat = obs_diff_rating, direction = "two_sided")

# With a p-value of 0.01 that is lower 0.05 we reject the null hypothesis and observe a significant difference

```

